### ISSUE TITLE
Pass options in CLI-like format to beautify method

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#162]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For Unibeautify to natively support passing of options in a CLI-like fashion for executables.  These would be the same options defined for the beautifier, such as [`indent_width`](https://github.com/Unibeautify/beautifier-sqlformat/blob/e300e9243fbbb070779f66e73027f8269471a4d1/src/options.ts#L13-L21). 99% (I made that number up) of executables use `--` as a prefix with `={value}`.  For example `--indent_width=2`.

**Describe alternatives you've considered**
Putting code that accomplishes this in the beautifier itself, which I've done with [sqlformat](https://github.com/Unibeautify/beautifier-sqlformat/blob/e300e9243fbbb070779f66e73027f8269471a4d1/src/index.ts#L69-L79).

**Additional context**

**Comment by Glavin001** [comment]
https://github.com/Unibeautify/beautifier-sqlformat/blob/e300e9243fbbb070779f66e73027f8269471a4d1/src/index.ts#L69-L79

```typescript
function transformOptionsToCli(options: Option) {
  return Object.keys(options).map(key => {
    const value = options[key];
    switch (typeof value) {
      case "boolean":
        return `--${key}`;
      default:
        return `--${key}=${value}`;
    }
  });
}
```

I do not think I support adding the above to Unibeautify core. It looks like an implementation detail for the beautifier itself. Multiple CLI/Executable based beautifiers may use similar function, so it may be a nice to have in a common library full of helper methods.

**Comment by szeck87** [comment]
Are you opposed to having them passed into the `beautify` method or having that above code in Unibeautify core?  Or Both?

> it may be a nice to have in a common library full of helper methods

That's why I thought the above code would work well in the [ExecutableDependency](https://github.com/Unibeautify/unibeautify/blob/master/src/DependencyManager/ExecutableDependency.ts) class.

**Comment by Glavin001** [comment]
> Are you opposed to having these processed options passed into the beautify method or having that above code in Unibeautify core? Or Both?

Opposed to adding `transformOptionsToCli` or similar method to Unibeautify core.
Adding to Beautifier's own `beautify` method implementation would be OK, as needed.

I think adding to `ExecutableDependency` class would make sense, however, since there are many different ways CLI's expect their arguments (e.g. `-arg value`, `--arg value`, `--arg=value`, etc) I think it makes more sense to implement this within the beautifier, as needed, and pass the `args` to Unibeautify within `beautify` method implementation: https://github.com/Unibeautify/unibeautify/blob/master/src/DependencyManager/ExecutableDependency.ts#L30  

All that being said, I do not think `transformOptionsToCli` is or should be used often. I prefer to have `args` represented as `string[]` and `push` to `args` as needed, for specific options, instead of creating an object / key-value and transforming into a `string[]` with a function like `transformOptionsToCli`.
