### ISSUE TITLE
CI job to check beautifiers are up-to-date with template

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify#194]
Would it be possible to create a CI job that:

* Uses the GitHub API to get the [list of all repos under the Unibeautify organization](https://api.github.com/orgs/Unibeautify/repos)
* Does shallow clones (`git clone --depth=1`) of all the `beautifier-` repos
* Checks the files in all those clones against the files in [beautifier-template](https://github.com/Unibeautify/beautifier-template), reporting any unusual divergences from template files.

Most of the time, the divergences would indicate that the beautifier in question is out of date compared to the template, i.e. we have neglected to update that beautifier.

**Comment by Glavin001** [comment]
This repo is for Unibeautify core library itself.
I think this issue sounds like it is better suited to be in https://github.com/Unibeautify/beautifier-template? You should be able to move it with https://github-issue-mover.appspot.com/ .

---

I like your line of thinking. We definitely need to keep the beautifiers up-to-date with best practices and such, especially since we have so many beautifiers now 🎉 .

I'm not confident this approach of diffing files will be effective unless we put significant effort into making it smarter to handle at least the handlebars templating (i.e. `{{` and `}}`). Furthermore, I'd like to keep the CI on point for building and validating code with tests / linters. Adding another step slows things down.

I would prefer to reduce the number of repeatedly copied files and potentially move them into a reusable package. Then let [Renovate](https://renovatebot.com/) tell us the repo's version of this reusable package is out of date -- easy.

For example, the following could be easily moved into a separate package:
- linting configuration: https://github.com/Unibeautify/beautifier-template/blob/master/tslint.json
- TypeScript compiler configuration: https://github.com/Unibeautify/beautifier-template/blob/master/tsconfig.json
- Unibeautify code formatting style guide: https://github.com/Unibeautify/beautifier-template/blob/master/.unibeautifyrc.yml
etc

I'd also like to add helpers to make writing tests easier. All of this could be in a reusable package which aids the development of Unibeautify beautifiers.

**Comment by lassik** [comment]
This issue was moved to Unibeautify/beautifier-template#53
