### ISSUE TITLE
Elm language support with elm-format beautifier

### ISSUE THREAD

**Issue by avh4** [Unibeautify/unibeautify#57]
Following up on @Glavin001's suggestion in https://github.com/avh4/elm-format/issues/459#issuecomment-369799919, 

what would be needed in order to add elm-format support to unibeautify?

**Comment by Glavin001** [comment]
Since `elm-format` is not written in JavaScript and therefore directly compatible with Node.js, adding support for this beautifier is blocked by https://github.com/Unibeautify/unibeautify/issues/58 . Once I have added `Executables` support (ported from Atom-Beautify) and create at least 1 beautifier to demonstrate, I will post back here and work with you to create the `elm-format` beautifier for Unibeautify 😃.

**Comment by avh4** [comment]
Okay, cool.  Ideally I would like to make elm-format available as an npm module as well (by compiling it with ghcjs), but unless I come across someone who wants to collaborate on that, I'm unlikely to get that to happen any time soon :)  But if I do happen to get that working, I'll let you know.

**Comment by Glavin001** [comment]
@avh4 if you can make a Node.js compatible version please let me know! This would make it a lot easier to get started developing a beautifier and is preferred to using a non-Node.js module.

**Comment by Glavin001** [comment]
Created repository https://github.com/Unibeautify/beautifier-elm-format . Closing this issue as any non-Unibeautify-core issues should be reported there.
